--liquibase formatted sql
--changeset lindomar:data-00

CREATE TABLE sexo (
    id  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sexo varchar(2)
);

CREATE TABLE procedimento (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    procedimento int
);

CREATE TABLE idade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    idade int
);

CREATE TABLE idade_procedimento (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      idade_id BIGINT,
      procedimento_id BIGINT,
      sexo_id BIGINT,
      executa_procedimento varchar(3)
  );

alter table idade_procedimento add constraint FK_idade_id foreign key (idade_id) references Idade (id);
alter table idade_procedimento add constraint FK_procedimento_id foreign key (procedimento_id) references Procedimento (id);
alter table idade_procedimento add constraint FK_sexo_id foreign key (sexo_id) references Sexo (id);

--rollback ALTER TABLE Sexo;
--rollback DROP TABLE Sexo;
--rollback ALTER TABLE Procedimento;
--rollback DROP TABLE Procedimento;
--rollback ALTER TABLE Idade;
--rollback DROP TABLE Idade;
--rollback ALTER TABLE IdadeProcedimento;
--rollback DROP TABLE IdadeProcedimento;