spring:
  h2.console:
    enabled: true
    path: /h2-console
    settings:
      web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: true
  jpa:
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  devtools:
    remote.secret: 123