FROM openjdk

EXPOSE 8080

WORKDIR /app

COPY target/sistemacontroleatutorizacaoprocedimentosmedicos-0.0.1-SNAPSHOT.jar /app/sistemacontroleatutorizacaoprocedimentosmedicos.jar

ENTRYPOINT ["java", "-jar", "sistemacontroleatutorizacaoprocedimentosmedicos.jar"]